// +build ignore

package main

import (
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"

	"github.com/iancoleman/strcase"
	"github.com/tallstoat/pbparser"
)

func getGoPackageName(pf pbparser.ProtoFile) string {
	for _, opt := range pf.Options {
		if opt.Name == "go_package" {
			return opt.Value
		}
	}
	return pf.PackageName
}

var zeroValues = map[string]string{
	"string": `""`,
	"bool":   `false`,
}

var fieldNameReplacer = strings.NewReplacer("Http", "HTTP", "Rpc", "RPC")

func toPublicFieldName(name string) string {
	return fieldNameReplacer.Replace(strings.Title(name))
}

func main() {
	var outDir = flag.String("o", ".", "OUT_DIR for the generated code.")
	flag.Parse()

	if len(flag.Args()) == 0 {
		fmt.Println(`Usage: generator PROTO_FILE
Parse PROTO_FILE and generate output value objects`)
		return
	}

	file := flag.Arg(0)
	pf, err := pbparser.ParseFile(file)
	if err != nil {
		fmt.Printf("Unable to parse proto file %q: %v \n", file, err)
		os.Exit(1)
	}

	fqpn := getGoPackageName(pf)
	pn := strings.Split(fqpn, "/")
	c := fmt.Sprintf("// Code generated by hypertrace/agent-config. DO NOT EDIT.\n\n")
	c += fmt.Sprintf("package %s\n\n", pn[len(pn)-1])

	for _, m := range pf.Messages {
		// add fields to the structs
		if len(m.Documentation) > 0 {
			c += "// " + m.Documentation + "\n"
		}
		c += fmt.Sprintf("type %s struct {\n", m.Name)
		for _, mf := range m.Fields {
			fieldName := toPublicFieldName(mf.Name)

			if len(mf.Documentation) > 0 {
				c += "    // " + mf.Documentation + "\n"
			}
			if messageType, ok := mf.Type.(pbparser.NamedDataType); ok {
				c += fmt.Sprintf("    %s *%s `json:\"%s,omitempty\"`\n", fieldName, messageType.Name(), mf.Name)
			} else {
				c += fmt.Sprintf("    %s *%s `json:\"%s,omitempty\"`\n", fieldName, mf.Type.Name(), mf.Name)
			}
		}
		c += "}\n\n"

		// adds getters to the structs
		for _, mf := range m.Fields {
			fieldName := toPublicFieldName(mf.Name)

			if messageType, ok := mf.Type.(pbparser.NamedDataType); ok {
				c += fmt.Sprintf("// Get%s returns the %s\n", fieldName, fieldName)
				c += fmt.Sprintf("func (x *%s) Get%s() *%s {\n", m.Name, fieldName, messageType.Name())
				c += fmt.Sprintf("    return x.%s\n", fieldName)
				c += "}\n\n"
			} else {
				c += fmt.Sprintf("// Get%s returns the %s\n", fieldName, mf.Name)
				c += fmt.Sprintf("func (x *%s) Get%s() %s {\n", m.Name, fieldName, mf.Type.Name())
				c += fmt.Sprintf("    return *x.%s\n", fieldName)
				c += "}\n\n"
			}
		}

		c += "// loadFromEnv loads the data from env vars, defaults and makes sure all values are initialized.\n"
		c += fmt.Sprintf("func (x *%s) loadFromEnv(prefix string, defaultValues *%s) {\n", m.Name, m.Name)
		for _, mf := range m.Fields {
			fieldName := toPublicFieldName(mf.Name)
			envPrefix := strings.ToUpper(strcase.ToSnake(mf.Name))
			if namedType, ok := mf.Type.(pbparser.NamedDataType); ok {
				c += fmt.Sprintf("    if x.%s == nil { x.%s = new(%s) }\n", fieldName, fieldName, namedType.Name())
				c += fmt.Sprintf("    x.%s.loadFromEnv(prefix + \"%s_\", defaultValues.%s)\n", fieldName, envPrefix, fieldName)
			} else {
				_type := mf.Type.Name()
				c += fmt.Sprintf("    if x.%s == nil { x.%s = new(%s) }\n", fieldName, fieldName, _type)
				c += fmt.Sprintf(
					"    if val, ok := get%sEnv(prefix + \"%s\"); ok {\n",
					strings.Title(_type),
					envPrefix,
				)
				c += fmt.Sprintf("        *x.%s = val\n", fieldName)
				c += fmt.Sprintf("    } else if *x.%s == %s && defaultValues != nil && defaultValues.%s != nil {\n", fieldName, zeroValues[_type], fieldName)
				c += fmt.Sprintf("        *x.%s = *defaultValues.%s\n", fieldName, fieldName)
				c += fmt.Sprintf("    }\n\n")
			}
		}
		c += "}\n\n"
	}

	baseFilename := filepath.Base(file)
	outputFile := baseFilename[0 : len(baseFilename)-6] // 6 = len(".proto")

	bc := []byte(c)
	fbc, err := format.Source(bc)
	if err != nil {
		fmt.Printf("failed to format the content, writing unformatted: %v\n", err)
		fbc = bc
	}

	err = writeToFile(*outDir+"/"+outputFile+".agentconfig.go", fbc)
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
}

func writeToFile(filename string, content []byte) error {
	f, err := os.Create(filename)
	if err != nil {
		return fmt.Errorf("failed to create file %q: %v", filename, err)
	}
	defer f.Close()
	_, err = f.Write(content)
	if err != nil {
		return fmt.Errorf("failed to write into file %q: %v", filename, err)
	}

	return nil
}
