name: test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go: [ '1.13', '1.14', '1.15' ]
    steps:
       # Set fetch-depth: 0 to fetch commit history and tags for use in version calculation
      - name: Check out code
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      
      - name: run tests
        run: |
          make deps
          make deps-ci 
          GO111MODULE=off go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
          make lint
          CGO_ENABLED=1 go test -coverprofile=coverage.txt -v ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          name: go-agent test reports
          fail_ci_if_error: true
          files: ./coverage.txt

      - name: check examples
        run: make check-examples