name: test
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
      - "LICENSE"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go: ["1.13", "1.14", "1.15", "1.16"]
    steps:
      # Set fetch-depth: 0 to fetch commit history and tags for use in version calculation
      - name: Check out code
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}

      - name: download dependencies
        run: |
          make deps

      - name: Lint files
        uses: golangci/golangci-lint-action@v2
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.29

      - name: Run tests
        run: CGO_ENABLED=1 go test -coverprofile=coverage.txt -v ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          name: go-agent test reports
          fail_ci_if_error: true
          files: ./coverage.txt

      - name: check examples
        run: make check-examples

  security:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/golang@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=low
