name: test
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
      - "LICENSE"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go: ["1.17", "1.18", "1.19"]
    steps:
      # Set fetch-depth: 0 to fetch commit history and tags for use in version calculation
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: Check go.mods
        uses: evantorrie/mott-the-tidier@v1-beta
        with:
          gomods: |
            **/go.mod

      - name: download dependencies
        run: |
          make deps

      - name: Lint files
        uses: golangci/golangci-lint-action@v3.4.0
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.50.1
          args: -v
          skip-pkg-cache: true
          only-new-issues: true

      - name: Run tests
        run: CGO_ENABLED=1 go test -coverprofile=coverage.txt -v ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          name: go-agent test reports
          fail_ci_if_error: true
          files: ./coverage.txt

      - name: check examples
        run: make check-examples

  security:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/golang@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=low
